# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklistdocument',
            fields=[
                ('checklistdocument_id', models.AutoField(primary_key=True, serialize=False)),
                ('random_field', models.CharField(blank=True, default='8211082', max_length=7, unique=True)),
                ('handover_date', models.DateField()),
                ('reminder_date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('handover_status', models.BooleanField()),
                ('handover_status_remark', models.TextField(blank=True)),
                ('form_handover', models.BooleanField()),
                ('form_bast', models.BooleanField()),
                ('scope_of_work', models.BooleanField()),
                ('scope_of_work_remark', models.CharField(blank=True, max_length=200)),
                ('project_approval', models.BooleanField()),
                ('project_approval_remark', models.CharField(blank=True, max_length=200)),
                ('purchase_order', models.BooleanField()),
                ('purchase_order_remark', models.CharField(blank=True, max_length=200)),
                ('sla', models.BooleanField()),
                ('sla_remark', models.CharField(blank=True, max_length=200)),
                ('business_case', models.BooleanField()),
                ('business_case_remark', models.CharField(blank=True, max_length=200)),
                ('proposal_to_customer_hld', models.BooleanField()),
                ('proposal_to_customer_hld_remark', models.CharField(blank=True, max_length=200)),
                ('proposal_to_customer_tda', models.BooleanField()),
                ('proposal_to_customer_tda_remark', models.CharField(blank=True, max_length=200)),
                ('partner_document_so_spk', models.BooleanField()),
                ('partner_document_so_spk_remark', models.CharField(blank=True, max_length=200)),
                ('product_spesification', models.BooleanField()),
                ('product_spesification_remark', models.CharField(blank=True, max_length=200)),
                ('implementation_document_lld', models.BooleanField()),
                ('implementation_document_lld_remark', models.CharField(blank=True, max_length=200)),
                ('wi_operation', models.BooleanField()),
                ('wi_operation_remark', models.CharField(blank=True, max_length=200)),
                ('wi_customer_care', models.BooleanField()),
                ('wi_customer_care_remark', models.CharField(blank=True, max_length=200)),
                ('contact_person_customer_vendor', models.BooleanField()),
                ('contact_person_customer_vendor_remark', models.CharField(blank=True, max_length=200)),
                ('handover_budget', models.BooleanField()),
                ('handover_budget_remark', models.CharField(blank=True, max_length=200)),
                ('user_acceptance_test', models.BooleanField()),
                ('user_acceptance_test_remark', models.CharField(blank=True, max_length=200)),
                ('bast_to_customer', models.BooleanField()),
                ('bast_to_customer_remark', models.CharField(blank=True, max_length=200)),
                ('bast_from_partner', models.BooleanField()),
                ('bast_from_partner_remark', models.CharField(blank=True, max_length=200)),
                ('no_jaringan_acuan', models.BooleanField()),
                ('no_jaringan_acuan_remark', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('table_updated', models.DateField(auto_now=True)),
                ('table_creation_timestamp', models.DateField(auto_now_add=True)),
                ('projectmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Lintasartaperson')),
            ],
        ),
    ]
