# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0016_auto_20181113_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdocument',
            name='random_field',
            field=models.CharField(blank=True, default='8172423', max_length=7, unique=True),
        ),
    ]
