# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0025_auto_20181129_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistdocument',
            name='random_field',
            field=models.CharField(blank=True, default='3595336', max_length=7, unique=True),
        ),
    ]
