# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assetmaster',
            fields=[
                ('asset_master_id', models.AutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(max_length=100)),
                ('no_registrasi', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, max_length=500)),
                ('table_updated', models.DateField(auto_now=True)),
                ('table_creation_timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('hw', 'Hardware'), ('sw', 'Software')], max_length=2)),
                ('spec', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_name', models.CharField(max_length=100)),
                ('type_license', models.CharField(choices=[('sub', 'Subsciption'), ('sup', 'Support'), ('per', 'Perpetual')], max_length=3)),
                ('license_start_date', models.DateField()),
                ('license_end_date', models.DateField()),
                ('remark', models.TextField(blank=True, max_length=500)),
                ('asset_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Assetmaster')),
            ],
        ),
        migrations.AddField(
            model_name='assetmaster',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Device'),
        ),
        migrations.AddField(
            model_name='assetmaster',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
