# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaster',
            name='location',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
