# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_contract', models.CharField(blank=True, max_length=100)),
                ('start_contract', models.DateField()),
                ('end_contract', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contracttype',
            fields=[
                ('contract_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_ho_address', models.CharField(blank=True, max_length=100)),
                ('customer_contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customersegment',
            fields=[
                ('customer_segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_segment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lintasartaperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('telp', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_jaringan', models.CharField(max_length=10)),
                ('keterangan', models.TextField(max_length=500)),
                ('jasa', models.CharField(max_length=100)),
                ('jenis_kecepatan', models.CharField(blank=True, max_length=100)),
                ('kecepatan', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_address', models.CharField(blank=True, max_length=100)),
                ('partner_contact_sales', models.CharField(blank=True, max_length=100)),
                ('partner_contact_support', models.CharField(blank=True, max_length=100)),
                ('partner_contact_manager', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_level', models.CharField(choices=[('c', 'Complex'), ('m', 'Medium'), ('s', 'Simple')], max_length=1)),
                ('scope_detail', models.TextField(max_length=1000)),
                ('scope_summary', models.TextField(max_length=500)),
                ('sla_availability', models.CharField(max_length=5)),
                ('sla_support_hour', models.CharField(choices=[('24x7', '24x7'), ('8x5', '8x5')], max_length=5)),
                ('sla_response_time', models.CharField(max_length=50)),
                ('sla_resolution_time', models.CharField(max_length=50)),
                ('descriptions', models.CharField(blank=True, max_length=100)),
                ('project_date_handover', models.DateField()),
                ('topology', models.ImageField(default='project/static/img/topo/no-img.jpg', upload_to='project/static/img/topo/')),
                ('contract_customer', models.CharField(max_length=500)),
                ('contract_partner', models.CharField(max_length=500)),
                ('purchase_order', models.CharField(max_length=500)),
                ('project_approval', models.CharField(max_length=500)),
                ('proposal_to_customer', models.CharField(max_length=500)),
                ('proposal_to_customer_sow', models.CharField(max_length=500)),
                ('proposal_to_customer_hld', models.CharField(max_length=500)),
                ('proposal_to_customer_boq', models.CharField(max_length=500)),
                ('proposal_from_partner', models.CharField(max_length=500)),
                ('proposal_from_partner_sow', models.CharField(max_length=500)),
                ('proposal_from_partner_boq', models.CharField(max_length=500)),
                ('implementation_document', models.CharField(max_length=500)),
                ('technical_data', models.CharField(max_length=500)),
                ('low_level_design', models.CharField(max_length=500)),
                ('business_case', models.CharField(max_length=500)),
                ('user_acceptance_test', models.CharField(max_length=500)),
                ('bast_to_customer', models.CharField(max_length=500)),
                ('partner_document', models.TextField(max_length=1000)),
                ('product_spesification', models.CharField(max_length=500)),
                ('bast_from_partner', models.CharField(max_length=500)),
                ('wi_operation', models.CharField(max_length=500)),
                ('wi_customer_care', models.CharField(max_length=500)),
                ('table_updated', models.DateField(auto_now=True)),
                ('table_creation_timestamp', models.DateField(auto_now_add=True)),
                ('car_lintasarta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_lintasarta', to='project.Lintasartaperson')),
                ('customer', models.ManyToManyField(to='project.Customer')),
                ('delivery_lintasarta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lintasarta', to='project.Lintasartaperson')),
                ('partner', models.ManyToManyField(to='project.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Projectstatus',
            fields=[
                ('project_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projectstatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_support_lintasarta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_support_lintasarta', to='project.Lintasartaperson'),
        ),
        migrations.AddField(
            model_name='project',
            name='sa_lintasarta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_lintasarta', to='project.Lintasartaperson'),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_lintasarta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_lintasarta', to='project.Lintasartaperson'),
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customersegment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Customersegment'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Contracttype'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
