# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partner_contact_manager',
            new_name='contact_manager_email',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_contact_sales',
            new_name='contact_manager_name',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partner_contact_support',
            new_name='contact_manager_telp',
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_sales_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_sales_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_sales_telp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_support_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_support_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_support_telp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_support_web',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_web',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
