# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180521_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectcategory',
            fields=[
                ('project_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='perpanjangan',
            field=models.CharField(blank=True, choices=[('ARO', 'ARO'), ('NON ARO', 'NON ARO')], max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='kelengkapan_dokumen',
            field=models.CharField(blank=True, choices=[('Lengkap', 'Lengkap'), ('Tidak Lengkap', 'Tidak Lengkap')], max_length=15),
        ),
    ]
