# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Projectstatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.Projectcategory'),
        ),
    ]
