# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20181113_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='kelengkapan_dokumen',
            field=models.CharField(choices=[('Tidak Lengkap', 'Tidak Lengkap'), ('Lengkap', 'Lengkap')], default='Tidak Lengkap', max_length=15),
        ),
    ]
