# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20181113_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Momserahterima',
            fields=[
                ('mom_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_location', models.CharField(blank=True, max_length=100)),
                ('mom_date_time', models.DateTimeField()),
                ('attendees', models.TextField(max_length=1000)),
                ('start_project', models.DateField()),
                ('end_project', models.DateField()),
                ('catatan_durasi_project', models.TextField(max_length=1000)),
                ('uraian_pekerjaan_pm', models.TextField(max_length=1000)),
                ('waktu_pelaksanaan_pm', models.TextField(max_length=1000)),
                ('lokasi_pm', models.TextField(max_length=1000)),
                ('daftar_perangkat_pm', models.TextField(max_length=1000)),
                ('catatan_pm', models.TextField(max_length=1000)),
                ('sla_to_customer', models.CharField(blank=True, max_length=100)),
                ('sla_to_partner', models.CharField(blank=True, max_length=100)),
                ('catatan_sla', models.TextField(max_length=1000)),
                ('anggaran_opex_perbulan_or_pertahun', models.CharField(blank=True, max_length=100)),
                ('anggaran_capex_perbulan_or_pertahun', models.CharField(blank=True, max_length=100)),
                ('total_anggaran_operational', models.CharField(blank=True, max_length=100)),
                ('catatan_anggaran_operational', models.TextField(max_length=1000)),
                ('scope_of_work', models.TextField(max_length=1000)),
                ('catatan_tambahan', models.TextField(max_length=1000)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Momserahterima_car', to='project.Lintasartaperson')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Momserahterima_delivery', to='project.Lintasartaperson')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Momserahterima_sa', to='project.Lintasartaperson')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Momserahterima_sales', to='project.Lintasartaperson')),
            ],
        ),
    ]
