# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_contractwithpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractwithpartner',
            name='partner',
            field=models.ManyToManyField(to='project.Partner'),
        ),
    ]
