# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20181127_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractwithpartner',
            fields=[
                ('contract_partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_contract', models.DateField()),
                ('end_contract', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
