# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_contractwithpartner_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momserahterima',
            name='anggaran_capex_perbulan_or_pertahun',
            field=models.IntegerField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='anggaran_opex_perbulan_or_pertahun',
            field=models.IntegerField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='total_anggaran_operational',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
