# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20181129_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momserahterima',
            name='car',
        ),
        migrations.RemoveField(
            model_name='momserahterima',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='momserahterima',
            name='sa',
        ),
        migrations.RemoveField(
            model_name='momserahterima',
            name='sales',
        ),
        migrations.AddField(
            model_name='momserahterima',
            name='contact',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='catatan_anggaran_operational',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='catatan_durasi_project',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='catatan_pm',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='catatan_sla',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='catatan_tambahan',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='daftar_perangkat_pm',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='end_project',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='lokasi_pm',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='sla_to_customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='sla_to_partner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='start_project',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='uraian_pekerjaan_pm',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='momserahterima',
            name='waktu_pelaksanaan_pm',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
